remote_theme: jackw01/jackw01.github.io
# used by SEO tag
title: alley cat engineering
description: the open source raspberry pi handheld retro gaming console
author:
  name: Jack Whittaker
  url: https://jackw01.github.io
logo: https://jackw01.github.io/logo.png
defaults:
  - scope:
      path: ""
    values:
      image: images/3dp_case_finished.jpg
social:
  name: Jack Whittaker
  links:
    - https://github.com/jackw01
    - https://www.linkedin.com/in/jack-whittaker-b35961183/
# end seo
alleycatengineering: true
hide_first_h1: true
title_h1_override: pi tin
plugins:
  - jekyll-seo-tag
nav_items:
  - 1:
    url: index
    text: Introduction
  - 2:
    url: hardware_build
    text: Electronics Build Guide
  - 3:
    url: software_setup
    text: Software Setup and Testing
  - 4:
    url: 3dp_assembly
    text: Final Assembly (3D Printed Version)
  - 5:
    url: altoids_assembly
    text: Final Assembly (Altoids Tin Version)
custom_buttons:
  - 1:
    url: https://sendfox.com/alleycatengineering
    text: Get notified when kits are available
  - 2:
    url: https://jackw01.github.io/pi-tin/3d/pi_tin_stl.zip
    text: Download STL files
  - 3:
    url: https://github.com/jackw01/pi-tin/releases/tag/v1.1
    text: Download SD card image
