remote_theme: jackw01/jackw01.github.io
title: pi tin
description: the open source raspberry pi handheld retro gaming console
alleycatengineering: true
github:
  is_project_page: false
hide_first_h1: true
plugins:
  - jekyll-seo-tag
nav_items:
  - 1:
    url: index
    text: Introduction
  - 2:
    url: hardware_build
    text: Electronics Build Guide
  - 3:
    url: software_setup
    text: Software Setup and Testing
  - 4:
    url: 3dp_assembly
    text: Final Assembly (3D Printed Version)
  - 5:
    url: altoids_assembly
    text: Final Assembly (Altoids Tin Version)
custom_buttons:
  - 1:
    url: https://github.com/jackw01/pi-tin/3d/pi_tin_stl.zip
    text: Download STL files
  - 2:
    url: https://github.com/jackw01/pi-tin/3d/pi_tin_stl.zip
    text: Download SD card image
  - 3:
    url: https://github.com/jackw01/pi-tin/3d/pi_tin_stl.zip
    text: Get notified when kits are available
